# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_hfun_nlqmm <- function(res, u, H, N, Q, tau, omicron) {
    .Call(`_nlqmm_C_hfun_nlqmm`, res, u, H, N, Q, tau, omicron)
}

C_loss_nlqmm <- function(res, u, weights, Psiinv, detH, detPsi, M, N, Q, sigma, tau, omicron) {
    .Call(`_nlqmm_C_loss_nlqmm`, res, u, weights, Psiinv, detH, detPsi, M, N, Q, sigma, tau, omicron)
}

